## LANGUAGE
defaultContentLanguage: sv
languageCode: sv

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
paginate: 9
removePathAccents: true
disableHugoGeneratorInject: true
timeout: 100000