imports:

# For content
# Choose section and taxonomies Hugolify module in this content available: https://github.com/Hugolify/hugolify-template/wiki/Content-sections
# Types
# - path: github.com/hugolify/hugolify-theme-casestudies
# - path: github.com/hugolify/hugolify-theme-expertises
- path: github.com/hugolify/hugolify-theme-persons
- path: github.com/hugolify/hugolify-theme-places
- path: github.com/hugolify/hugolify-theme-posts
# - path: github.com/hugolify/hugolify-theme-products
- path: github.com/hugolify/hugolify-theme-projects
- path: github.com/hugolify/hugolify-theme-publications
# - path: github.com/hugolify/hugolify-theme-services
- path: github.com/hugolify/hugolify-theme-persons
# Taxonomies
- path: github.com/hugolify/hugolify-theme-posts-authors
- path: github.com/hugolify/hugolify-theme-posts-categories
- path: github.com/hugolify/hugolify-theme-publications-categories
# - path: github.com/hugolify/hugolify-theme-services-categories
- path: github.com/hugolify/hugolify-theme-persons-expertises
- path: github.com/hugolify/hugolify-theme-publications-persons
# - path: github.com/hugolify/hugolify-theme-services-persons
- path: github.com/hugolify/hugolify-theme-persons-places
- path: github.com/hugolify/hugolify-theme-persons-statutes
- path: github.com/hugolify/hugolify-theme-posts-tags
- path: github.com/hugolify/hugolify-theme-projects-tags
- path: github.com/hugolify/hugolify-theme-projects-types

# Core theme required
- path: github.com/hugolify/hugolify-theme

# CMS
- path: github.com/hugolify/hugolify-netlify-cms
